// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/orch.proto

package orchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeEvent_EventType int32

const (
	NodeEvent_JOIN    NodeEvent_EventType = 0
	NodeEvent_LEAVE   NodeEvent_EventType = 1
	NodeEvent_DEAD    NodeEvent_EventType = 2
	NodeEvent_SUSPECT NodeEvent_EventType = 3
)

// Enum value maps for NodeEvent_EventType.
var (
	NodeEvent_EventType_name = map[int32]string{
		0: "JOIN",
		1: "LEAVE",
		2: "DEAD",
		3: "SUSPECT",
	}
	NodeEvent_EventType_value = map[string]int32{
		"JOIN":    0,
		"LEAVE":   1,
		"DEAD":    2,
		"SUSPECT": 3,
	}
)

func (x NodeEvent_EventType) Enum() *NodeEvent_EventType {
	p := new(NodeEvent_EventType)
	*p = x
	return p
}

func (x NodeEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orch_proto_enumTypes[0].Descriptor()
}

func (NodeEvent_EventType) Type() protoreflect.EnumType {
	return &file_proto_orch_proto_enumTypes[0]
}

func (x NodeEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeEvent_EventType.Descriptor instead.
func (NodeEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{9, 0}
}

type ScaleSignal_Direction int32

const (
	ScaleSignal_OUT ScaleSignal_Direction = 0
	ScaleSignal_IN  ScaleSignal_Direction = 1
)

// Enum value maps for ScaleSignal_Direction.
var (
	ScaleSignal_Direction_name = map[int32]string{
		0: "OUT",
		1: "IN",
	}
	ScaleSignal_Direction_value = map[string]int32{
		"OUT": 0,
		"IN":  1,
	}
)

func (x ScaleSignal_Direction) Enum() *ScaleSignal_Direction {
	p := new(ScaleSignal_Direction)
	*p = x
	return p
}

func (x ScaleSignal_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScaleSignal_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orch_proto_enumTypes[1].Descriptor()
}

func (ScaleSignal_Direction) Type() protoreflect.EnumType {
	return &file_proto_orch_proto_enumTypes[1]
}

func (x ScaleSignal_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScaleSignal_Direction.Descriptor instead.
func (ScaleSignal_Direction) EnumDescriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{10, 0}
}

type NodeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	IsLeader      bool                   `protobuf:"varint,5,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	Term          uint64                 `protobuf:"varint,6,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeId) Reset() {
	*x = NodeId{}
	mi := &file_proto_orch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeId) ProtoMessage() {}

func (x *NodeId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeId.ProtoReflect.Descriptor instead.
func (*NodeId) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{0}
}

func (x *NodeId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeId) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NodeId) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *NodeId) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeId) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *NodeId) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeId                `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	ClusterToken  uint64                 `protobuf:"varint,2,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	KnownPeers    []string               `protobuf:"bytes,3,rep,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_orch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNode() *NodeId {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Hello) GetClusterToken() uint64 {
	if x != nil {
		return x.ClusterToken
	}
	return 0
}

func (x *Hello) GetKnownPeers() []string {
	if x != nil {
		return x.KnownPeers
	}
	return nil
}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeId                `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	ClusterView   []*NodeId              `protobuf:"bytes,2,rep,name=cluster_view,json=clusterView,proto3" json:"cluster_view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_proto_orch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAck) GetNode() *NodeId {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *HelloAck) GetClusterView() []*NodeId {
	if x != nil {
		return x.ClusterView
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeId                `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemUsage      float32                `protobuf:"fixed32,4,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	Goroutines    uint32                 `protobuf:"varint,5,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_orch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetNode() *NodeId {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Heartbeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Heartbeat) GetMemUsage() float32 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *Heartbeat) GetGoroutines() uint32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Helper        *NodeId                `protobuf:"bytes,2,opt,name=helper,proto3" json:"helper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_orch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Ping) GetHelper() *NodeId {
	if x != nil {
		return x.Helper
	}
	return nil
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Target        *NodeId                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_proto_orch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{5}
}

func (x *PingReq) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PingReq) GetTarget() *NodeId {
	if x != nil {
		return x.Target
	}
	return nil
}

type PingAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Helper        *NodeId                `protobuf:"bytes,2,opt,name=helper,proto3" json:"helper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingAck) Reset() {
	*x = PingAck{}
	mi := &file_proto_orch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingAck) ProtoMessage() {}

func (x *PingAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingAck.ProtoReflect.Descriptor instead.
func (*PingAck) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{6}
}

func (x *PingAck) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PingAck) GetHelper() *NodeId {
	if x != nil {
		return x.Helper
	}
	return nil
}

type PingReqAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Target        *NodeId                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Alive         bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReqAck) Reset() {
	*x = PingReqAck{}
	mi := &file_proto_orch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReqAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReqAck) ProtoMessage() {}

func (x *PingReqAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReqAck.ProtoReflect.Descriptor instead.
func (*PingReqAck) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{7}
}

func (x *PingReqAck) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PingReqAck) GetTarget() *NodeId {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PingReqAck) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type GossipEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           uint32                 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	MsgId         uint64                 `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipEnvelope) Reset() {
	*x = GossipEnvelope{}
	mi := &file_proto_orch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipEnvelope) ProtoMessage() {}

func (x *GossipEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipEnvelope.ProtoReflect.Descriptor instead.
func (*GossipEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{8}
}

func (x *GossipEnvelope) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *GossipEnvelope) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GossipEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type NodeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NodeEvent_EventType    `protobuf:"varint,1,opt,name=type,proto3,enum=orch.v1.NodeEvent_EventType" json:"type,omitempty"`
	Node          *NodeId                `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Term          uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_proto_orch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{9}
}

func (x *NodeEvent) GetType() NodeEvent_EventType {
	if x != nil {
		return x.Type
	}
	return NodeEvent_JOIN
}

func (x *NodeEvent) GetNode() *NodeId {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeEvent) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type ScaleSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     ScaleSignal_Direction  `protobuf:"varint,1,opt,name=direction,proto3,enum=orch.v1.ScaleSignal_Direction" json:"direction,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Delta         uint32                 `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleSignal) Reset() {
	*x = ScaleSignal{}
	mi := &file_proto_orch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleSignal) ProtoMessage() {}

func (x *ScaleSignal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleSignal.ProtoReflect.Descriptor instead.
func (*ScaleSignal) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{10}
}

func (x *ScaleSignal) GetDirection() ScaleSignal_Direction {
	if x != nil {
		return x.Direction
	}
	return ScaleSignal_OUT
}

func (x *ScaleSignal) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ScaleSignal) GetDelta() uint32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *ScaleSignal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RequestVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   uint64                 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVote) Reset() {
	*x = RequestVote{}
	mi := &file_proto_orch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVote) ProtoMessage() {}

func (x *RequestVote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVote.ProtoReflect.Descriptor instead.
func (*RequestVote) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{11}
}

func (x *RequestVote) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVote) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVote) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVote) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReply) Reset() {
	*x = RequestVoteReply{}
	mi := &file_proto_orch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReply) ProtoMessage() {}

func (x *RequestVoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReply.ProtoReflect.Descriptor instead.
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{12}
}

func (x *RequestVoteReply) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReply) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  uint64                 `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   uint64                 `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  uint64                 `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntries) Reset() {
	*x = AppendEntries{}
	mi := &file_proto_orch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntries) ProtoMessage() {}

func (x *AppendEntries) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntries.ProtoReflect.Descriptor instead.
func (*AppendEntries) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{13}
}

func (x *AppendEntries) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntries) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntries) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntries) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntries) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntries) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesReply) Reset() {
	*x = AppendEntriesReply{}
	mi := &file_proto_orch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReply) ProtoMessage() {}

func (x *AppendEntriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReply.ProtoReflect.Descriptor instead.
func (*AppendEntriesReply) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{14}
}

func (x *AppendEntriesReply) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Command       []byte                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_orch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{15}
}

func (x *LogEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_orch_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orch_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_orch_proto_rawDescGZIP(), []int{16}
}

func (x *ErrorResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_orch_proto protoreflect.FileDescriptor

const file_proto_orch_proto_rawDesc = "" +
	"\n" +
	"\x10proto/orch.proto\x12\aorch.v1\"\x91\x01\n" +
	"\x06NodeId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1b\n" +
	"\tis_leader\x18\x05 \x01(\bR\bisLeader\x12\x12\n" +
	"\x04term\x18\x06 \x01(\x04R\x04term\"r\n" +
	"\x05Hello\x12#\n" +
	"\x04node\x18\x01 \x01(\v2\x0f.orch.v1.NodeIdR\x04node\x12#\n" +
	"\rcluster_token\x18\x02 \x01(\x04R\fclusterToken\x12\x1f\n" +
	"\vknown_peers\x18\x03 \x03(\tR\n" +
	"knownPeers\"c\n" +
	"\bHelloAck\x12#\n" +
	"\x04node\x18\x01 \x01(\v2\x0f.orch.v1.NodeIdR\x04node\x122\n" +
	"\fcluster_view\x18\x02 \x03(\v2\x0f.orch.v1.NodeIdR\vclusterView\"\xa8\x01\n" +
	"\tHeartbeat\x12#\n" +
	"\x04node\x18\x01 \x01(\v2\x0f.orch.v1.NodeIdR\x04node\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tmem_usage\x18\x04 \x01(\x02R\bmemUsage\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x05 \x01(\rR\n" +
	"goroutines\"N\n" +
	"\x04Ping\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12'\n" +
	"\x06helper\x18\x02 \x01(\v2\x0f.orch.v1.NodeIdR\x06helper\"Q\n" +
	"\aPingReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12'\n" +
	"\x06target\x18\x02 \x01(\v2\x0f.orch.v1.NodeIdR\x06target\"Q\n" +
	"\aPingAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12'\n" +
	"\x06helper\x18\x02 \x01(\v2\x0f.orch.v1.NodeIdR\x06helper\"j\n" +
	"\n" +
	"PingReqAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12'\n" +
	"\x06target\x18\x02 \x01(\v2\x0f.orch.v1.NodeIdR\x06target\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\"S\n" +
	"\x0eGossipEnvelope\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\rR\x03ttl\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x04R\x05msgId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xaf\x01\n" +
	"\tNodeEvent\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.orch.v1.NodeEvent.EventTypeR\x04type\x12#\n" +
	"\x04node\x18\x02 \x01(\v2\x0f.orch.v1.NodeIdR\x04node\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\"7\n" +
	"\tEventType\x12\b\n" +
	"\x04JOIN\x10\x00\x12\t\n" +
	"\x05LEAVE\x10\x01\x12\b\n" +
	"\x04DEAD\x10\x02\x12\v\n" +
	"\aSUSPECT\x10\x03\"\xb1\x01\n" +
	"\vScaleSignal\x12<\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x1e.orch.v1.ScaleSignal.DirectionR\tdirection\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\rR\x05delta\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x1c\n" +
	"\tDirection\x12\a\n" +
	"\x03OUT\x10\x00\x12\x06\n" +
	"\x02IN\x10\x01\"\x8e\x01\n" +
	"\vRequestVote\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x04R\vlastLogTerm\"I\n" +
	"\x10RequestVoteReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\xdc\x01\n" +
	"\rAppendEntries\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x04R\vprevLogTerm\x12+\n" +
	"\aentries\x18\x05 \x03(\v2\x11.orch.v1.LogEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x04R\fleaderCommit\"B\n" +
	"\x12AppendEntriesReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"N\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x18\n" +
	"\acommand\x18\x03 \x01(\fR\acommand\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB,Z*github.com/orch-protocol/orch/proto;orchpbb\x06proto3"

var (
	file_proto_orch_proto_rawDescOnce sync.Once
	file_proto_orch_proto_rawDescData []byte
)

func file_proto_orch_proto_rawDescGZIP() []byte {
	file_proto_orch_proto_rawDescOnce.Do(func() {
		file_proto_orch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orch_proto_rawDesc), len(file_proto_orch_proto_rawDesc)))
	})
	return file_proto_orch_proto_rawDescData
}

var file_proto_orch_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_orch_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_orch_proto_goTypes = []any{
	(NodeEvent_EventType)(0),   // 0: orch.v1.NodeEvent.EventType
	(ScaleSignal_Direction)(0), // 1: orch.v1.ScaleSignal.Direction
	(*NodeId)(nil),             // 2: orch.v1.NodeId
	(*Hello)(nil),              // 3: orch.v1.Hello
	(*HelloAck)(nil),           // 4: orch.v1.HelloAck
	(*Heartbeat)(nil),          // 5: orch.v1.Heartbeat
	(*Ping)(nil),               // 6: orch.v1.Ping
	(*PingReq)(nil),            // 7: orch.v1.PingReq
	(*PingAck)(nil),            // 8: orch.v1.PingAck
	(*PingReqAck)(nil),         // 9: orch.v1.PingReqAck
	(*GossipEnvelope)(nil),     // 10: orch.v1.GossipEnvelope
	(*NodeEvent)(nil),          // 11: orch.v1.NodeEvent
	(*ScaleSignal)(nil),        // 12: orch.v1.ScaleSignal
	(*RequestVote)(nil),        // 13: orch.v1.RequestVote
	(*RequestVoteReply)(nil),   // 14: orch.v1.RequestVoteReply
	(*AppendEntries)(nil),      // 15: orch.v1.AppendEntries
	(*AppendEntriesReply)(nil), // 16: orch.v1.AppendEntriesReply
	(*LogEntry)(nil),           // 17: orch.v1.LogEntry
	(*ErrorResponse)(nil),      // 18: orch.v1.ErrorResponse
}
var file_proto_orch_proto_depIdxs = []int32{
	2,  // 0: orch.v1.Hello.node:type_name -> orch.v1.NodeId
	2,  // 1: orch.v1.HelloAck.node:type_name -> orch.v1.NodeId
	2,  // 2: orch.v1.HelloAck.cluster_view:type_name -> orch.v1.NodeId
	2,  // 3: orch.v1.Heartbeat.node:type_name -> orch.v1.NodeId
	2,  // 4: orch.v1.Ping.helper:type_name -> orch.v1.NodeId
	2,  // 5: orch.v1.PingReq.target:type_name -> orch.v1.NodeId
	2,  // 6: orch.v1.PingAck.helper:type_name -> orch.v1.NodeId
	2,  // 7: orch.v1.PingReqAck.target:type_name -> orch.v1.NodeId
	0,  // 8: orch.v1.NodeEvent.type:type_name -> orch.v1.NodeEvent.EventType
	2,  // 9: orch.v1.NodeEvent.node:type_name -> orch.v1.NodeId
	1,  // 10: orch.v1.ScaleSignal.direction:type_name -> orch.v1.ScaleSignal.Direction
	17, // 11: orch.v1.AppendEntries.entries:type_name -> orch.v1.LogEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_orch_proto_init() }
func file_proto_orch_proto_init() {
	if File_proto_orch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orch_proto_rawDesc), len(file_proto_orch_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_orch_proto_goTypes,
		DependencyIndexes: file_proto_orch_proto_depIdxs,
		EnumInfos:         file_proto_orch_proto_enumTypes,
		MessageInfos:      file_proto_orch_proto_msgTypes,
	}.Build()
	File_proto_orch_proto = out.File
	file_proto_orch_proto_goTypes = nil
	file_proto_orch_proto_depIdxs = nil
}
